Fix compilation with rustc 1.21.
I added the quickcheck crate to gamenet/Cargo.toml because it was used in gamenet/src/lib.rs,
and updated the minor version of mio so it uses a newer version of 'nix', which was raising
this error:

```
error[E0591]: can't transmute zero-sized type
   --> /home/teeworlds/.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.4.2/src/sched.rs:168:20
    |
168 |         ffi::clone(mem::transmute(callback), ptr as *mut c_void, flags, &mut cb)
    |                    ^^^^^^^^^^^^^^
    |
    = note: source type: extern "C" fn(*mut std::boxed::Box<std::ops::FnMut() -> isize>) -> i32 {sched::clone::callback}
    = note: target type: *const extern "C" fn(*const std::boxed::Box<std::ops::FnMut() -> isize>) -> i32
    = help: cast with `as` to a pointer instead
```