uniffi/huffman: Fix maturin error about project.version
```
💥 maturin failed
  Caused by: `project.version` field is required in pyproject.toml unless it is present in the `project.dynamic` list
Error: command ['maturin', 'pep517', 'write-sdist', '--sdist-directory', 'dist'] returned non-zero exit status 1
```